export const AGREGAR_GASTO = 'AGREGAR_GASTO';
export const CANCELAR_REINICIO_FORM_GASTOS = 'CANCELAR_REINICIO_FORM_GASTOS';
export const ELIMINAR_GASTOS = 'ELIMINAR_GASTOS';
export const ELIMINAR_GASTO = 'ELIMINAR_GASTO;';
export const ACTIVAR_EDICION_GASTO = 'ACTIVAR_EDICION_GASTO;';
export const CANCELAR_EDICION_GASTO = 'CANCELAR_EDICION_GASTO;';
export const EDITAR_GASTO = 'EDITAR_GASTO;';