export const ESTABLECER_PRESUPUESTO = 'ESTABLECER_PRESUPUESTO';
export const OBTENER_PRESUPUESTO = 'OBTENER_PRESUPUESTO';
export const ELIMINAR_PRESUPUESTO = 'ELIMINAR_PRESUPUESTO';
export const RESTAR_PRESUPUESTO = 'RESTAR_PRESUPUESTO';
export const SUMAR_PRESUPUESTO_GASTO_BORRADO = 'SUMAR_PRESUPUESTO_GASTO_BORRADO';
export const ACTUALIZAR_RESTANTE = 'ACTUALIZAR_RESTANTE';